
#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  customize: !include  customize.yaml
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
discovery:
stream:
logger:
  default: warn
http:
  ip_ban_enabled: true

#################################################################
## Components
#################################################################



# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
